### ISSUE TITLE
Recall Product Image

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#12]
As a consumer user, I want to see a photo of the the product so that I can confirm the exact item being recalled.

Acceptance Criteria:
1. Display photo of recalled item as a part of the recall information

**Comment by shavensKPMG** [comment]
![recall-description-prod-image](https://cloud.githubusercontent.com/assets/13007398/8339918/f50484ac-1a88-11e5-932f-bf122da84291.png)
