### ISSUE TITLE
Recall Severity Visualization

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#13]
As a consumer user, I want to see the severity of active recalls to determine if any pose a health risk.

Acceptance Criteria:
1. Display pie chart of active recalls by Class

**Comment by jardilio-kpmg** [comment]
Example query structs:

All Coconut in 2012 regardless of Status, counts by Classification
https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20120101+TO+20121231]&count=classification

All Coconut with Status of Ongoing, counts by Classification
https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+status:Ongoing&count=classification

We should be able to utilize the existing FoodEnforcementService$getResultsByKeywords method and pass the count:'classification' into the options parameter object. Will need to add a new unit test to cover this scenario.

**Comment by jcornwell-kpmg** [comment]
![04 severity 2015 - v1](https://cloud.githubusercontent.com/assets/13000971/8338425/0668436e-1a7f-11e5-9866-f0fbb010bdad.jpg)
