### ISSUE TITLE
Product Recall History

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#15]
As a consumer user, I want to see a recalls over time so that I can find any trends in product quality.

Acceptance Criteria:
1. Display number of recalls as a stacked bar chart for the past 5 years by classification

**Comment by jardilio-kpmg** [comment]
OpenFDA’s API doesn’t support / implement this function
o   http://opendata.stackexchange.com/questions/3525/is-it-possible-to-receive-complaint-count-in-monthly-format
·          We will need to make multiple round trips… one query per year (as postulated previously)
o   https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20100101+TO+20101231]&count=classification
o   https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20110101+TO+20111231]&count=classification
o   https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20120101+TO+20121231]&count=classification
o   https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20130101+TO+20131231]&count=classification
o   https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20140101+TO+20141231]&count=classification
o   https://api.fda.gov/food/enforcement.json?search=product_description:Coconut+AND+report_date:[20150101+TO+20151231]&count=classification
·         The only other alternative I can think of is a 3 round trips (one for each classification with large payload back) and a script to consolidate dates.
o   https://api.fda.gov/food/enforcement.json?search=classification-i-&count=report_date
o   https://api.fda.gov/food/enforcement.json?search=classification-ii-&count=report_date
o   https://api.fda.gov/food/enforcement.json?search=classification-iii-&count=report_date

**Comment by jardilio-kpmg** [comment]
![image](https://cloud.githubusercontent.com/assets/12973322/8381248/83e6ad74-1bf8-11e5-849f-aa6910d3f975.png)

**Comment by jcornwell-kpmg** [comment]
We'll need data in this structure to support the NVD3 grouped/stacked bar chart:
[ { key: "Class I", values: [ { x: 2011, y:  65}, { x: 2012, y:  91}, { x: 2013, y: 290}, { x: 2014, y: 44}, { x: 2015, y: 321} ] } ]
