### ISSUE TITLE
Sort search results by class

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#27]
Order search results by class with Class I appearing at the top, followed by Class II and Class III.

![sort](https://cloud.githubusercontent.com/assets/13002867/8356520/e027c616-1b23-11e5-8b30-57449059706b.PNG)

**Comment by jardilio-kpmg** [comment]
Cap request at max (100?) and sort client side (no pagination/infinate scroll)
