### ISSUE TITLE
Display "Recall Details" instead of event id in title

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#29]
Instead of displaying the event id, display "Recall Details" in the title.

![recalldetail](https://cloud.githubusercontent.com/assets/13002867/8356701/db03d57a-1b24-11e5-8014-a66154cf1e46.PNG)

**Comment by jardilio-kpmg** [comment]
Also, need to remove the ":" after the report date label field
