### ISSUE TITLE
Reorder fields in Recall Details page

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#31]
1. Move product description panel to top
2. Move distribution to product description panel under Reason for Recall
3. Add recall initiation date under report date

**Comment by mtross-kpmg** [comment]
![recalldetail](https://cloud.githubusercontent.com/assets/13002867/8360017/0d85100a-1b38-11e5-864f-f8efaa579da2.PNG)

**Comment by jvillarreal-kpmg** [comment]
@mtross-kpmg 
Just to confirm,
Does the 'Initiation' text should go in place of 'Status'?

**Comment by mtross-kpmg** [comment]
Can you include the initiation date between report date and status date so the fields appear in the following order in the card:

Class
Report Date
Initiation Date
Status
