### ISSUE TITLE
Keyword search does not bring up expected results

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#32]
Entering UPC: 073230008665 in the keyword search does not return any results. 
Entering Keyword: Prince Oysters Chili returns one result where the code info contains - UPC 073230008665, Case Code 00073230228667, CPI Item # 866.

Expected UPC search to return the same result as keyword search.

For reference - UPC: 032100023429 returns one result as expected.

**Comment by jardilio-kpmg** [comment]
Need to add 2 separate input fields to search on barcode OR keywords

**Comment by jardilio-kpmg** [comment]
need implement state management here as well for: search, searching, no results, results
