### ISSUE TITLE
Update initial search page layout

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#34]
![img_0163](https://cloud.githubusercontent.com/assets/13002867/8361308/687815e0-1b40-11e5-8175-60af1db91eba.JPG)

**Comment by mtross-kpmg** [comment]
Replace "Let's Get Started!" with "Is My Food Safe?"
In smaller text below add Check Food Recalls Now...

**Comment by shavensKPMG** [comment]
![openfda_mobile-home](https://cloud.githubusercontent.com/assets/13007398/8387083/eeebba08-1c23-11e5-94ca-a9cee89e7526.png)

**Comment by shavensKPMG** [comment]
![openfda_mobile-home](https://cloud.githubusercontent.com/assets/13007398/8387101/1c1730b6-1c24-11e5-840e-3206abe8fa93.png)

**Comment by jvillarreal-kpmg** [comment]
Reopening with new change.
