### ISSUE TITLE
Recall Search

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#4]
As a consumer user, I want to look up a product so that I can find out if it has been recalled.

Acceptance Criteria:
1. Scan product barcode
2. Display search results

**Comment by jardilio-kpmg** [comment]
![image](https://cloud.githubusercontent.com/assets/12973322/8313058/6bd76daa-19ae-11e5-86b3-eb8910abfa84.png)

![image](https://cloud.githubusercontent.com/assets/12973322/8313095/9ae7c8b0-19ae-11e5-8d87-07d6d7f3ca0c.png)

![image](https://cloud.githubusercontent.com/assets/12973322/8313027/355ba23c-19ae-11e5-9e05-c227f65c7701.png)
