### ISSUE TITLE
Keyword, UPC, Barcode search screen updates

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#52]
Can we change the title from “Relevant Recalls” to “Search”? Instead of “Barcode” use “UPC” – for the label and button? Remove the word “Any” from the “Scan Any Barcode” button.

![image 02](https://cloud.githubusercontent.com/assets/13002867/8421420/58cb248e-1e9c-11e5-8550-f4c8ef42b224.JPG)

**Comment by jcornwell-kpmg** [comment]
Changes committed and waiting on approval of PR#67.
