### ISSUE TITLE
Could not read barcode message appears after clicking on keyword search button

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#55]
Steps to Recreate:
1. From the splash page, click the Scan Barcode button
2. Select upc-a_894180000017.jpg (attached) from desktop
3. Click on Enter Keyword or UPC button
4. Whoops! I couldn't read... message appears

![upc-a_894180000017](https://cloud.githubusercontent.com/assets/13002867/8433100/c663b964-1f11-11e5-8c91-6aa2500b69c7.jpg)

![capture 01](https://cloud.githubusercontent.com/assets/13002867/8433095/be2c23bc-1f11-11e5-804c-b1b4c7253751.PNG)

**Comment by jardilio-kpmg** [comment]
Sounds like a digest cycle may not be occurring here? Possibly need a applyAsync or issue with our stacking the http requests until animations finish.

**Comment by jvillarreal-kpmg** [comment]
Resolved on https://github.com/jardilio-kpmg/ads-rfq-prototype/pull/68.
Dialogs were working but z-index were making dialogs to show behind the view.
