### ISSUE TITLE
Trends page not refreshing after new search

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#56]
Steps to Recreate:
1. Enter "coffee" in the keyword search and click Search by Keywords
2. Click on Trends
3. Click on the search icon to go back to search input screen
4. Change "coffee" to "pineapple" and click Search by Keywords
5. The Trends do not reflect the new search

Trends refresh seems to be intermittent.

**Comment by jardilio-kpmg** [comment]
May be a data load issue here where calls are taking a while to resolve, may need to flush out old results on new search while we wait.

**Comment by jcornwell-kpmg** [comment]
Changes committed and waiting on approval of PR#69.
