### ISSUE TITLE
UPC Not Found clicking NO THANKS displays page with loading icon

### ISSUE THREAD

**Issue by mtross-kpmg** [jardilio-kpmg/ads-rfq-prototype#57]
Steps to Recreate:
1. From the search screen enter "894180000017" in the UPC search field and click the Search button
2. The following message appears:
![capture 02](https://cloud.githubusercontent.com/assets/13002867/8433384/63f7f720-1f13-11e5-9069-31dc5d58d06e.PNG)
3. Clicking NO THANKS closes the message and displays a page with loading icon

**Comment by shavensKPMG** [comment]
Perhaps this screen should have a prompt that says some to the effect of "Try a new keyword Search" To give the user a clear option that they can try a new search with a keyword of their choosing.

**Comment by jcornwell-kpmg** [comment]
I'm going to leave the "No Thanks" label for now. At smaller resolutions (e.g. iPhone 4) longer text is being cut off.

**Comment by jcornwell-kpmg** [comment]
Changes committed and waiting on approval of PR#65.
